---
- name: Check mount point
  stat: path={{ item.mount_point }}
  register: stats

- name: Check that if mount point already exists or not.
  fail: msg="{{ item.mount_point }} already exists. Remove it and re-run."
  when: stats.stat.exists

- name: Create physical volume on selected disk or partition
  command: pvcreate -ffy {{ backup_disk }}

- name: Create volume group
  command: vgcreate {{ item.volume_group }} {{ backup_disk }}

- name: Create logical volume
  command: lvcreate -n {{ item.logical_volume }} -l 100%FREE {{ item.volume_group }}

- name: Create filesystem
  command: mkfs.ext4 -T largefile /dev/mapper/{{ item.volume_group }}-{{ item.logical_volume }}

- name: Mount and update /etc/fstab
  mount:
    name: "{{ item.mount_point }}"
    src: /dev/mapper/{{ item.volume_group }}-{{ item.logical_volume }}
    fstype: ext4
    passno: 2
    state: mounted
