- include_tasks: validate.yml
  tags: [ validate, always ]

- include_tasks: hostname.yml
  tags: hostname

- include_tasks: groups.yml
  tags: groups

- include_tasks: users.yml
  tags: users

- include_tasks: hosts.yml
  tags: hosts
