- include_tasks: validate.yml
  tags: [ validate, always ]

- include_tasks: hostname.yml
  tags: hostname

- include_tasks: hosts.yml
  tags: hosts

- include_tasks: groups.yml
  tags: groups

- include_tasks: users.yml
  tags: users

- include_tasks: packages.yml
  tags: packages

- include_tasks: backupdisk.yml
  tags: backupdisk
  with_items:
    - '{{ backup_disk_default }}'
  when: backup_disk is defined

